<?php

/**
 * @file
 */

/**
 * Implements hook_mail().
 */
function atlas_peer_invite_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'send_assessment_link':
      $site_name = \Drupal::config('system.site')->get('name');
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['sender_username'] . ' wants you to rate them at ' . $site_name;
      $message['body'][] = $params['message'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  }
}
