# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://atlas.{default}/":
    type: upstream
    upstream: "app:http"

"https://second.{default}/":
    type: upstream
    upstream: "app:http"
