mysqldb:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - logindb
            - luckcompaniesdb
        endpoints:
            atlas:
                default_schema: logindb
                privileges:
                    atlasdb: admin
            luckcompanies:
                default_schema: luckcompaniesdb
                privileges:
                    luckcompaniesdb: admin
