mysqldb:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - logindb
            - luckcompaniesdb
        endpoints:
            login:
                default_schema: logindb
                privileges:
                    logindb: admin
            luckcompanies:
                default_schema: luckcompaniesdb
                privileges:
                    luckcompaniesdb: admin
rediscache:
    type: redis:5.0                    
