mysqldb:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - atlasdb
            - luckcompaniesdb
            - atlastenantdb
        endpoints:
            atlas:
                default_schema: atlasdb
                privileges:
                    atlasdb: admin
            luckcompanies:
                default_schema: luckcompaniesdb
                privileges:
                    luckcompaniesdb: admin
            atlastenant:
                default_schema: atlastenantdb
                privileges:
                    atlastenantdb: admin
