database:
    type: "mysql:10.0"
    disk: 2048
    configuration:
        schemas:
            - atlasdb
            - seconddb
        endpoints:
            atlas:
                default_schema: atlasdb
                privileges:
                    atlasdb: admin
            second:
                default_schema: seconddb
                privileges:
                    seconddb: admin